//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestKorea.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string Current {
            get {
                return ((string)(this["Current"]));
            }
            set {
                this["Current"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>GeForce GTX 1080</string>
  <string>Radeon RX 580</string>
  <string>Radeon R9 Fury</string>
  <string>GeForce GTX 1060 6GB</string>
  <string>GeForce GTX 1080 TI</string>
  <string>Nvidia Titan XP</string>
  <string>Radeon R9 Nano</string>
  <string>Radeon R9 390X</string>
  <string>Radeon R9 Fury X</string>
  <string>Radeon R9 390</string>
  <string>Radeon RX 580</string>
  <string>Radeon RX 560</string>
  <string>GeForce GTX 1070</string>
  <string>Radeon RX 380</string>
  <string>Radeon RX 480</string>
  <string>Radeon RX 470</string>
  <string>Radeon RX 460</string>
  <string>Radeon R9 360X</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection gpus {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["gpus"]));
            }
            set {
                this["gpus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unknown")]
        public string InstalledGPU {
            get {
                return ((string)(this["InstalledGPU"]));
            }
            set {
                this["InstalledGPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LogFile {
            get {
                return ((bool)(this["LogFile"]));
            }
            set {
                this["LogFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>1szb </string>\r\n  <string>1Ex </string>\r\n  <string>247exchange </string>\r\n" +
            "  <string>24change</string>\r\n  <string>796</string>\r\n  <string>Alcurex</string>\r" +
            "\n  <string>alfacashier</string>\r\n  <string>alts</string>\r\n  <string>anxpro</stri" +
            "ng>\r\n  <string>askcoin</string>\r\n  <string>basebit</string>\r\n  <string>bit2c</st" +
            "ring>\r\n  <string>bitebi9</string>\r\n  <string>bitex</string>\r\n  <string>bitbay</s" +
            "tring>\r\n  <string>bitcoin.com</string>\r\n  <string>bitcoin.net</string>\r\n  <strin" +
            "g>bitcointoyou</string>\r\n  <string>Bitcurex</string>\r\n  <string>Bitfinex</string" +
            ">\r\n  <string>bitflyer</string>\r\n  <string>bitkonan</string>\r\n  <string>bitmex</s" +
            "tring>\r\n  <string>bitnz</string>\r\n  <string>bitonic</string>\r\n  <string>bitorado" +
            "</string>\r\n  <string>bitso</string>\r\n  <string>bitstamp</string>\r\n  <string>Bitt" +
            "rex </string>\r\n  <string>bittylicious</string>\r\n  <string>bitx/market</string>\r\n" +
            "  <string>Bleutrade </string>\r\n  <string>bloombit </string>\r\n  <string>bt</strin" +
            "g>\r\n  <string>btc2day </string>\r\n  <string>btc38 </string>\r\n  <string>btc100 </s" +
            "tring>\r\n  <string>btcbox </string>\r\n  <string>btcchina </string>\r\n  <string>btc-" +
            "e </string>\r\n  <string>btcexchange </string>\r\n  <string>btcgreece</string>\r\n  <s" +
            "tring>btcpool </string>\r\n  <string>btctrader </string>\r\n  <string>btcxchange </s" +
            "tring>\r\n  <string>bter </string>\r\n  <string>Blaketrader </string>\r\n  <string>bx " +
            "</string>\r\n  <string>c-cex </string>\r\n  <string>campbx </string>\r\n  <string>cced" +
            "k </string>\r\n  <string>cex </string>\r\n  <string>chameleonbit </string>\r\n  <strin" +
            "g>chbtc </string>\r\n  <string>clevercoin </string>\r\n  <string>coinbase </string>\r" +
            "\n  <string>coincheck</string>\r\n  <string>coinffeine </string>\r\n  <string>coinflo" +
            "or </string>\r\n  <string>coingather </string>\r\n  <string>coinmate </string>\r\n  <s" +
            "tring>coingather </string>\r\n  <string>coinomat </string>\r\n  <string>coinsbank </" +
            "string>\r\n  <string>coinspot </string>\r\n  <string>coinsquare </string>\r\n  <string" +
            ">cryptofresh/assets </string>\r\n  <string>cryptomic </string>\r\n  <string>cryptoni" +
            "t</string>\r\n  <string>cryptopia </string>\r\n  <string>dashcurex </string>\r\n  <str" +
            "ing>ecoin </string>\r\n  <string>empirex </string>\r\n  <string>empoex </string>\r\n  " +
            "<string>exmo </string>\r\n  <string>eXrate </string>\r\n  <string>gdax </string>\r\n  " +
            "<string>gemini </string>\r\n  <string>hitbtc </string>\r\n  <string>huobi </string>\r" +
            "\n  <string>ice3x </string>\r\n  <string>Iconomi </string>\r\n  <string>indacoin </st" +
            "ring>\r\n  <string>itbit </string>\r\n  <string>jubi</string>\r\n  <string>justcoin </" +
            "string>\r\n  <string>kraken </string>\r\n  <string>leoxchange </string>\r\n  <string>l" +
            "itebit </string>\r\n  <string>livecoin </string>\r\n  <string>localbitcoins </string" +
            ">\r\n  <string>loyalbit </string>\r\n  <string>melotic </string>\r\n  <string>mercurye" +
            "x </string>\r\n  <string>metaexchangefo </string>\r\n  <string>mexbt </string>\r\n  <s" +
            "tring>monatr </string>\r\n  <string>monetago</string>\r\n  <string>mycellium </strin" +
            "g>\r\n  <string>negociecoins </string>\r\n  <string>x-e </string>\r\n  <string>okcoin " +
            "</string>\r\n  <string>poloniex </string>\r\n  <string>quadrigacx </string>\r\n  <stri" +
            "ng>quoine </string>\r\n  <string>shapeshift southxchange therocktrading traderowbt" +
            "c usecryptos</string>\r\n  <string>vaultoro </string>\r\n  <string>vircurex </string" +
            ">\r\n  <string>yobit </string>\r\n  <string>yuanbaohui </string>\r\n  <string>yunbi </" +
            "string>\r\n  <string>zaif</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Sites {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Sites"]));
            }
            set {
                this["Sites"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Logging {
            get {
                return ((bool)(this["Logging"]));
            }
            set {
                this["Logging"] = value;
            }
        }
    }
}
